### ISSUE TITLE
IModelState Crash

### ISSUE THREAD

**Issue by LatvianModder** [ChiselsAndBits/FlatColoredBlocks#15]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 16.21.3 20:28
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/IModelState
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:241)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/IModelState
    at mod.flatcoloredblocks.model.ModelGenerator.preinit(ModelGenerator.java:59)
    at mod.flatcoloredblocks.client.ClientSide.preinit(ClientSide.java:44)
    at mod.flatcoloredblocks.FlatColoredBlocks.preinit(FlatColoredBlocks.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.IModelState
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 39 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 41 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 726593816 bytes (692 MB) / 1034420224 bytes (986 MB) up to 2386558976 bytes (2276 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2560m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.23 Powered by Forge 12.16.0.1781 18 mods loaded, 18 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.0.1781-1.9.jar) 
    UCH Forge{12.16.0.1781} [Minecraft Forge](forge-1.9-12.16.0.1781-1.9.jar) 
    UCH armorplus{1.6} [ArmorPlus](ArmorPlus-1.7%281.9%29.jar) 
    UCH betterbuilderswands{0.5.1} [Better Builder's Wands](BetterBuildersWands-0.5.1-1.9r86+a001294.jar) 
    UCH Chameleon{1.9-2.0.0} [Chameleon](Chameleon-1.9-2.0.0.jar) 
    UCH chisel{3.0} [Chisel 3](Chisel Dev-3.0.jar) 
    UCH mcmultipart{1.1.0} [MCMultiPart](MCMultiPart-1.1.0-universal.jar) 
    UCH chiselsandbits{9.3} [Chisels & Bits](chiselsandbits-9.3.jar) 
    UCE flatcoloredblocks{mc1.9-v2.0} [Flat Colored Blocks](flatcoloredblocks-mc1.9-v2.0.jar) 
    UCH inventorysorter{0.7.8+28} [Simple Inventory sorting](inventorysorter-1.9-0.7.8+28.jar) 
    UCH IronChest{6.0.126.771} [Iron Chest](ironchest-1.9-6.0.126.771.jar) 
    UCH JEI{3.0.3.166} [Just Enough Items](jei_1.9-3.0.3.166.jar) 
    UCH journeymap{1.9-5.1.5b3} [JourneyMap](journeymap-1.9-5.1.5b3-unlimited.jar) 
    UCH Morpheus{1.9-3.0.1} [Morpheus](Morpheus-1.9-3.0.1.jar) 
    UCH Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat](Neat 1.2-4.jar) 
    UCH fuj1n.recmod{v1.5.2} [Recording Status Mod](RecStatusMod-1.9-v1.5.2.jar) 
    UCH StorageDrawers{1.9-3.0.0} [Storage Drawers](StorageDrawers-1.9-3.0.0.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.12002 Compatibility Profile Context 9.12.0.0' Renderer: 'AMD Radeon HD 7660D'

**Comment by AlgorithmX2** [comment]
Resolved By https://github.com/AlgorithmX2/FlatColoredBlocks/commit/6bcaa7cb48c1d7201923a4927e3e58422646811b

**Comment by LatvianModder** [comment]
So I need to downgrade forge until this fix is released?

**Comment by AlgorithmX2** [comment]
Its already released.

**Comment by LatvianModder** [comment]
Thanks!
