### ISSUE TITLE
Compatibility issues with Optifine

### ISSUE THREAD

**Issue by AYuPro** [ChiselsAndBits/FlatColoredBlocks#25]
When FlatColoredBlocks and Optifine run together error occurse on main menu, and console filled with 

[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]: java.lang.reflect.**InvocationTargetException**
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at java.lang.reflect.Method.invoke(Unknown Source)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at Reflector.callVoid(Reflector.java:336)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1399)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at net.minecraft.client.main.Main.main(SourceFile:124)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at java.lang.reflect.Method.invoke(Unknown Source)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[22:43:10] [Client thread/INFO]: [Reflector:handleException:914]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:43:10] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: **java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting**
[22:43:10] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]:  at mod.flatcoloredblocks.gui.GuiScreenStartup.func_73863_a(GuiScreenStartup.java:53)
[22:43:10] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]:  at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
[22:43:10] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]:  ... 14 more

**Comment by AlgorithmX2** [comment]
For some reason with optifine installed, the realmsclient classes are missing, not sure why that would be. Sounds like an issue on its own.

That said I used the wrong class, and switched to the TextFormatting class instead which is what is normally used, which will probobly resolve the issue.

https://minecraft.curseforge.com/projects/flat-colored-blocks/files/2338922

But to be frank, this crash isn't FCB's fault.
